### ISSUE TITLE
multiple event binding

### ISSUE THREAD

**Issue by Jinkwon** [ftlabs/ftdomdelegate#68]
Hi,
First of all, very appreciate to your good lib.
I need multiple event binding such as,

AS-IS
```
myDelegate.on('mousedown', '.icon', changeClass).on('mouseup', '.icon', changeClass);
```

TO-BE
```
myDelegate.on('mousedown mouseup', '.icon', changeClass);
```

Could you consider this?
Thanks.

**Comment by matthew-andrews** [comment]
we used to support this but we found that doing this was very much the exception in all of our codebases and we decided that keeping the library as small as possible was more important than a rarely used piece of convenience sugar……

It would be quite simple to wrap dom delegate to add this function…

```js
(function() {
var oldOn = Delegate.prototype.on;
Delegate.prototype.on = function(events) {
  var args = Array.prototype.slice.call(arguments);
  events.split(' ').forEach(function(event) {
    args[0] = event;
    oldOn.apply(this, args);
  }, this);
};
}());
```

is adding this to codebase in order to add this feature an acceptable alternative for you?

**Comment by Jinkwon** [comment]
@matthew-andrews 
I agree with that. It will be helpful for me.
BTW, really wonderful lib for my lightweight project.
Thanks so much.

**Comment by matthew-andrews** [comment]
You're welcome :smile:
